DROP TABLE IF EXISTS TIMED_COMMANDS;
 
CREATE TABLE TIMED_COMMANDS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  command VARCHAR(250) NOT NULL,
  time_of_execution TIMESTAMP WITH TIME ZONE DEFAULT NULL 
);
 
/*
INSERT INTO TIMED_COMMANDS (command, time_of_execution) VALUES
  ('PWR ON TRANSPONDER', '2019-07-09T10:15:30Z'),
  ('ROTATE SOLAR PANEL +X 45 DEGREES CCW', '2019-07-09T10:17:45Z')
  */